### PR TITLE
Added 4 elven subraces, tiefling and svirfneblin .

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by DudeMcDude** [comment]
Very nice! Are you planning to add more?

**Comment by doug1234** [comment]
I was thinking of adding Svirfneblin which I am about 50% done with to this pull request.  Then I'll be done.

**Comment by doug1234** [comment]
Added  Svirfneblin.  Should be ready to send to the master branch if you don't see anything that needs to be changed.

**Comment by DudeMcDude** [comment]
Did you forget to commit the svirfnebin? I'm not seeing it...

**Comment by DudeMcDude** [comment]
Oops, I guess I just missed it. Nevermind, merged!

**Pull request merged**
