### PR TITLE
Modified grease  to a 5 foot radius

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by DudeMcDude** [comment]
I know this is how it should be by the rules, but I have no doubt players would be pissed off by this. Let's leave it be.

**Comment by doug1234** [comment]
How about a config option?  I hate to leave an obvious bug like this and I am pretty sure some will like it.

**Comment by DudeMcDude** [comment]
Good idea. Let's call it "Stricter rules enforcement" for that sort of thing.
On that note, having a donut shape for reach weapons fits that as well.

**Comment by doug1234** [comment]
Sounds like we are on the same page.  A donut shape for reach weapons is high on my list of things I would like to see.  I'll add the "Stricter rules enforcement" option shortly.

**Comment by doug1234** [comment]
For donut correcting reach weapons, what would need to be done?  Would modifying CanMeleeTargetAtLocRegardItem, CanMeleeTargetFromLocRegardItem and CanMeleeTargetRegardWeapon be enough?

**Pull request merged**
