### PR TITLE
Divine Spell Power, Quicken Turn Undead, Fast Wild Shape, bug 071 fix, Staggering Strike, Sudden Extend, Sudden Still, Sudden Silent

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by doug1234** [comment]
Added quicken Turn Undead.

**Comment by doug1234** [comment]
I thought DivineSpellPowerEffect = PythonModifier("Divine Spell Power Effect", 4) gave me 4 args.  My plan was to have extras I could use later...

**Comment by doug1234** [comment]
I changed the feat to use the same parameter as the effect to avoid any possible issue.  But wasn't the effect the one that needed the four parameters?  Also added fast wild shape.

**Comment by DudeMcDude** [comment]
Yeah that's my mistake, I didn't notice it was a different modifier. You can change it back.

**Comment by doug1234** [comment]
Added Staggering Strike.  

Unless you feel strongly about it I'd just leave it the way it is.  Having both with 4 is less confusing and I don't think there is much downside.

BTW:  Is there anything else you need me to change before you can add the changes to the branch?

**Comment by doug1234** [comment]
Added sudden extend.

**Comment by doug1234** [comment]
Good suggestion.  I am now using the object.

**Comment by doug1234** [comment]
I was making it a query to be similar caster level modify.  But what you are asking for makes more sense.  There is no object that seems perfect so I'll make my own that is only metamagic data.

**Comment by doug1234** [comment]
Hopefully it looks good now.  Also added sudden still and silent.

**Pull request merged**
