### PR TITLE
PerformBreakFree update and Inflict touch fix

### PR DESCRIPTION
**Pull request by anatoliy-savchak**
* PerformBreakFree updated with better code; tested;
* Inflict spell fixed to use melee, not ranged touch attack; tested;

### CODE REVIEW

**Comment by doug1234** [comment]
A few comments:
(1)  Are you sure the inflict/cure spells being ranged touch attacks were a mistake and not written that way to work around other issues.
(2)  Seems like heal/harm could use a similar change...
(3)  It would be nice if they really worked correctly (so you could hold a charge).  Maybe a future fix?

**Comment by anatoliy-savchak** [comment]
1) I suspect melee argument of touch function was added later. But currently it is obviously a mistake.
2) I agree, will alter, test and supply commit. Good point!
3) Yes I agree, that it would be nice to have. But I consider it rather niche functionality. Perhaps later.

**Comment by DudeMcDude** [comment]
> 1. I suspect melee argument of touch function was added later. But currently it is obviously a mistake.
Yes, originally it was always ranged touch attack. I think for Searing Light. I added the flag for the vampiric touch fix.

**Comment by anatoliy-savchak** [comment]
@doug1234 can you approve it? I think everyone has agreed on the changes.

**Comment by doug1234** [comment]
Sorry about that.  I thought you were going to add the code you showed us on co8.  Merging now.

**Comment by anatoliy-savchak** [comment]
@doug1234 - I did included counter* API and Inflict fixes into the Pull Request :)
The only thing I did not do is Harm, which I moved down in my backlog, as it is not critical at this moment.

**Pull request merged**
