### PR TITLE
Spell Heart Ripper from the SC

### PR DESCRIPTION
**Pull request by Sagenlicht**
@dolio 
This spell contains a modified spell_utils. I often need to check if a target has a certain mc_type, and I finally added the check to the spell_utils.

### CODE REVIEW

**Comment by DudeMcDude** [comment]
Is this still a WIP? It looks finished...

**Comment by Sagenlicht** [comment]
Is there a better way to handle the XP issue? Other than that the spell is pretty much done and I tested it a fair amount already.

**Comment by DudeMcDude** [comment]
Ah ok cool.
I think in temple+ you can add an arg to the "kill by effect" call that denotes who the attacker is, so you don't have to apply manual damage.

**Comment by Sagenlicht** [comment]
Ah ty for pointing this out to me. Fixed

**Comment by DudeMcDude** [comment]
> Ah ty for pointing this out to me. Fixed

Yeah I added it for the Assassin :)

BTW there's a bunch of user bug reports on the Spell Compendium thread, can you look into it?

**Pull request merged**
