### PR TITLE
Added Silent Moves and Shadow to craft options

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by DudeMcDude** [comment]
Don't forget to add to changelog!

**Comment by doug1234** [comment]
Change log updated.

**Comment by DudeMcDude** [comment]
Are you planning on adding anything more? Otherwise I want to release this weekend.

**Comment by doug1234** [comment]
Just merged it in.  I have some more stuff I will do related to crafting but that can be in another version.  Do you think this version has been tested enough?  If so, I could do the release on Friday if you want.

BTW:  I noticed that if you turn on the stacking metamagic, extra empower does not seem to have an effect.  Is that OK for this version?

**Comment by DudeMcDude** [comment]
> Just merged it in. I have some more stuff I will do related to crafting but that can be in another version. Do you think this version has been tested enough? If so, I could do the release on Friday if you want.
> 
> BTW: I noticed that if you turn on the stacking metamagic, extra empower does not seem to have an effect. Is that OK for this version?

Yeah, no biggie.
Friday it is!

**Pull request merged**
