### PR TITLE
debug.breakp

### PR DESCRIPTION
**Pull request by anatoliy-savchak**
Added debug.breakp enbedded function for debugging python code from T+

### CODE REVIEW

**Comment by doug1234** [comment]
Sounds interesting.  Could you please explain how to make use of it?

**Comment by anatoliy-savchak** [comment]
All Python code I debug using VS with T+ in debug mode. I set a breakpoint in the BreakP function. Therefore when Python breakp() call happens I can understand where I am, which callback is being used. 

For example code I use:
`
def create_guard_at(loc):
	PROTO_NPC_MAN = 14000
	newDescription = game.make_custom_name('Gatehouse Guard')
	npc = game.obj_create(PROTO_NPC_MAN, loc) # man

	npc.obj_set_int(obj_f_critter_description_unknown, newDescription)
	npc.obj_set_int(obj_f_description_correct, newDescription)

	npc_feats_print(npc)
	breakp("npc_feats_print")
	obj_scripts_clear(npc)
	item_clear_all(npc)
	# armor
	item_create_in_inventory(PROTO_ARMOR_LEATHER_ARMOR_MASTERWORK, npc)
	# helm
	item_create_in_inventory(PROTO_HELMS_LEATHER_CAP, npc)
	# hands
	item_create_in_inventory(PROTO_GLOVES_PADDED_TAN, npc)
	# boots
	item_create_in_inventory(PROTO_BOOTS_PADDED_TAN, npc)
	# melee
	item_create_in_inventory(PROTO_WEAPON_SHORTSWORD, npc)
	# ranged
	item_create_in_inventory(PROTO_WEAPON_SHORTBOW_COMPOSITE_12_MASTERWORK, npc)
	item_create_in_inventory(PROTO_AMMO_ARROW_QUIVER, npc)
	npc.item_wield_best_all()

	npc.feat_add(feat_point_blank_shot, 0)
	npc.feat_add(feat_precise_shot, 0)
	npc.feat_add(feat_sneak_attack, 0)
	npc.condition_add_with_args("Sneak_Attack", 0, 0)
	npc.condition_add_with_args("Rogue", 0, 0)#check!

	npc.stat_base_set(stat_strength, 13)
	npc.stat_base_set(stat_dexterity, 15)
	npc.stat_base_set(stat_constitution, 14)
	npc.stat_base_set(stat_intelligence, 12)
	npc.stat_base_set(stat_wisdom, 10)
	npc.stat_base_set(stat_charisma, 8)

	npc.make_class(stat_caster_level_rogue, 1)
	npc.npc_flag_unset(ONF_NO_ATTACK)
	npc_generate_hp(npc)
	npc_money_set(npc, 31*gp)
	npc.obj_set_int(obj_f_npc_challenge_rating, 1)
	npc.scripts[sn_start_combat] = 6111
	return npc
`

@doug1234, can we also talk on co8.org forum? Name is anatoliy there.

**Comment by doug1234** [comment]
Thanks for the explanation.  I am _doug_ on co8.org.  You can send me a private message there or respond to the long message thread in General Modification called "Temple+ Modding Question".

**Comment by DudeMcDude** [comment]
@shartte on that note, i vaguely recall we had discussed python debugging... got anything to add on the subject?

**Comment by shartte** [comment]
@DudeMcDude Yes, it should be possible to use a Python debugger by importing the respective Python module. As far as I know, no native code is actually required for this.

With regards to this change: I am of two minds here, I can see why anatoliy would make use of it, but I personally wouldn't merge it since there should be better alternatives. Either by making use of actual Python debugging (see the `pdb` module), or by actually making this function trigger a native breakpoint directly (by calling__debugbreak on the native side).
I searched around for a bit, but was unable to find any standard Python function that would trigger int3 (this is what __debugbreak() does in the MSVC compiler) to drop to the attached native debugger, so if we add sth like this function, it should a) return PyNone and b) call __debugbreak()

**Comment by anatoliy-savchak** [comment]
__debugbreak() is an exception, which have to be dealt with. See here: https://www.codeproject.com/Articles/10022/DebugBreak-and-ASSERTs-that-work-always-anywhere

Ending with similar to that article's PreDebugBreakAnyway()

@shartte , are you sure to go this way? Perhaps manual breakpoint toggle would suffice?

**Comment by shartte** [comment]
@anatoliy-savchak You could also wrap __debugbreak() in IsDebuggerPresent() to ignore it when no debugger is attached already. Other than that, I don't _really_ see the purpose of the function in question. What would you use it for over directly attaching a python debugger?

**Comment by anatoliy-savchak** [comment]
@shartte, I find that function to be extremely useful for Python scrip development in many cases.
For example, I can see call stack of where it is being called from T+ code.
Or I can "pause" Python print messages, parse log it visually and understand what is going on. Then "continue" with process in mind.

I can also use it to see if san event is even triggered (much faster than parsing huge load of log). 
Or to see if and when condition event is triggered. I already created quite a few.

As for debugging Python - I don't see how can I attach devenv to it. Only old way print and pause (T+ breakpoint) works.

**Comment by anatoliy-savchak** [comment]
@DudeMcDude, can you approve or deny this pull request then?

**Comment by DudeMcDude** [comment]
If the discussion is concluded, I'm ok with that.

**Pull request merged**
