### PR TITLE
 No longer allowing sneak attack against concealed creatures, telling blow support for scout and freedom armor

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by doug1234** [comment]
Of course not!  I don't make copy past errors.  The favored scout class is my favorite class in 3.5 edition.

I'll get that fixed Monday. :)

**Comment by DudeMcDude** [comment]
Hi, can you update the dat files?

**Comment by doug1234** [comment]
I'll take care of that later this week.  I also have one more thing I would like to add to the pull request.

**Comment by doug1234** [comment]
Should be ready to go now!

**Pull request merged**
