### PR TITLE
Mirror Image error due to changing get_metamagic_data return type

### PR DESCRIPTION
**Pull request by DudeMcDude**
Heads up: @anatoliy-savchak @dolio @doug1234 @Sagenlicht 
I don't know if you've used this anywhere, but the spell_packet method get_metamagic_data() has been changed from returning integer to tpdp.MetaMagicData object. (This borked the Mirror Image script, which was just caught by a playtester)

### CODE REVIEW

**Comment by Sagenlicht** [comment]
The deal_spell_damage  function in damage_critter.py uses this.

**Comment by DudeMcDude** [comment]
I know, that's why I changed the API in the first place ;)

**Comment by doug1234** [comment]
Thanks for the heads up.  I'll look through some other scripts and see if it might be causing problems.  

BTW:  Is there still a way to get the metamagic data as an integer in python?

**Comment by DudeMcDude** [comment]
No. Though I'd rather the python side dealt with the object rather than expose the internals of how the bytes are packed, in case we ever change it.

**Pull request merged**
