### PR TITLE
Added lingering song, fixed leve 20 bard inspire courage bug, augment healing, Wolverine's Rage and Versatile Unarmed Strike

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by IPDTFE** [comment]
I haven't read all of the code for lingering song, but it seems you've added the 3.0 version from song and silence. Wouldn't it be better to use the [3.5 version](http://dnd.arkalseif.info/feats/complete-adventurer--54/lingering-song--1776/index.html)?

**Comment by doug1234** [comment]
Good find.  I'll update it to specify the 3.5 version.

If I understand it correctly, the feat works the same in both versions:  5 rounds doubled or 5 round and 5 more rounds is 10 rounds (1 minute).

**Comment by IPDTFE** [comment]
Except for inspire confidence, but the implementation seems to be correct for the 3.5 version

**Comment by doug1234** [comment]
I see... the 3.5 version effects a different set of bard abilities than the 3.0 version.  The 3.5 version was the version I implemented despite citing the wrong book.

**Comment by doug1234** [comment]
Sorry about the typo.  :(  I will fix that shortly.  

I don't understand your comment about OnDamage.  The bonus for augment healing is to healing.

**Comment by DudeMcDude** [comment]
The SpellHeal() function internally does a dispatch for event type 22, but as it turns out it's performed by the heal receiver and not the heal giver. It also doesn't broadcast the spell id. So I guess a new event type is warranted. But I think it should be named "Spell Healing Bonus" rather than Healing Bonus, since it assumes a spell id in the d20query?
If you want to broaden it to include non-spell healing you'll need to handle spell ID = 0 in the py script.

**Comment by doug1234** [comment]
I saw there was an on heal received type event but that wouldn't really do what I wanted.  I can send out the "Healing Bonus" query from non spell healing with an id of zero.  Then I'll make sure I do nothing when the id is zero in the Augment Healing feat (I assume it would break otherwise).

BTW:  Is there a way to test for a valid spell id?  That would be the best way to handle things in Augment Healing.

**Comment by DudeMcDude** [comment]
IIRC the accepted way is to test spell enum nonzero.

**Comment by doug1234** [comment]
Thanks.  I'll get it finished up later this week.

**Comment by doug1234** [comment]
Should be good to go.

**Comment by doug1234** [comment]
Wolverine's Rage feat.

**Comment by DudeMcDude** [comment]
No, I'm on vacation till sept 29. October probably.

**Comment by doug1234** [comment]
Added Versatile Unarmed Strike and some cleanup.

**Comment by DudeMcDude** [comment]
The issue with duplicates should be fixed now, so the check for wild shaped condition should be superfluous. Also merged :)

**Comment by doug1234** [comment]
Thanks!  I'll check it later this week.

**Pull request merged**
