### PR TITLE
Fixed a concerning warning.

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by DudeMcDude** [comment]
That's a great catch! Now I'm wondering if that was the cause of the crashes reported during beta... damn!

**Comment by DudeMcDude** [comment]
It wasn't. Oh well.

**Comment by doug1234** [comment]
Would have been nice if it fixed everything but probably still worth merging in when ever we are ready to start merging stuff again.

**Comment by DudeMcDude** [comment]
Ah, for sure. Can you also do PR for the bugfix branch?

**Comment by doug1234** [comment]
Sure.  Which branch is that?

**Comment by DudeMcDude** [comment]
Fearures branch is simply named features :)

Fixes branch is called Hotfixes 1.0.84.1 or sthg like that. But you can create a new branch that's forked from master, since that one is quite a bit behind (i can always just cherry pick).

**Pull request merged**
