### PR TITLE
Added Battle Caster.

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by doug1234** [comment]
I am not sure what you mean by generic queries.  Do you mean that the query should have a more generic name?  I couldn't come up with anything better than the name I gave it.  Any suggestions?

**Comment by DudeMcDude** [comment]
I mean that instead of checking an explicit list of classes with armored casting, the classes should have a property designating them as such.

**Comment by doug1234** [comment]
Interesting idea but how would I make it work correctly when taking the first level of a class?  For example if a level 2 fighter takes a level of bard, they should be able to take the feat that level.  I don't think that would work correctly using a query.

**Comment by DudeMcDude** [comment]
Yeah I didn't mean d20query, just a bool property you can query via the D20classSys.

**Comment by doug1234** [comment]
OK.  I get it now.  I'll make an update some time next week.

**Comment by doug1234** [comment]
Should be good to go now.

**Comment by doug1234** [comment]
The list is now compiled only one time now.

**Pull request merged**
