### PR TITLE
game.combat_turn and Path constructors fix

### PR DESCRIPTION
**Pull request by anatoliy-savchak**
* pathfinding.h - better fix of PathQueryResult.nodeCount not initializing;
* python_game.cpp - added game.combat_round Python API;
* ui_intgame_turnbased.cpp - remove obsolate debug print;
* animgoals_callbacks - fixed IsConcealed on non-critter;
* traps.h - figured out  unknown fields in Trap;

### CODE REVIEW

**Comment by doug1234** [comment]
Looks pretty uncontroversial to me.  I am going to go ahead and merge it in.

**Comment by DudeMcDude** [comment]
Why did you remove the debug print? What's obsolete about it?

**Comment by anatoliy-savchak** [comment]
> Why did you remove the debug print? What's obsolete about it?

I assume debug print for cursor changing was very handy during cursor fixes. But now when it is polished, it spams debug output to the point of complete unusability. Sometime I cannot see nothing but hundreds of "cursor changed" notifications.

I was hesitant to make this change, as someone added it to help test cursor changes. That is nice, and I honor it. But now it works stable and there is no necessity to leave it, that is why it is obsolete.

**Comment by DudeMcDude** [comment]
It's strange that you see it toggle so much. I don't recall seeing anything like that. It could be an actual problem you're glossing over. Why would it change so many times?

**Comment by anatoliy-savchak** [comment]
I guess it is related to moving mouse from game to devenv on other monitor to see logs, then back again and so forth. It flies over cursor-changing objects and spams debug window.

I can uncomment it if you like. No issue here.

**Comment by DudeMcDude** [comment]
In general, we need all the help we can get when figuring out user submitted bug reports. I guess this one isn't so important, but you never know. I'd rather keep it.

**Pull request merged**
