### PR TITLE
Secret Door port

### PR DESCRIPTION
**Pull request by anatoliy-savchak**
Port of Secret Door functions. No alterations.

### CODE REVIEW

**Comment by anatoliy-savchak** [comment]
@doug1234, may I ask you to make code review? This is port from IDA, no changes.

**Comment by doug1234** [comment]
One thing has me a bit confused.  What's up with SecretdoorDetect in obj.h?  Should it be changed to call you function directly?

**Comment by anatoliy-savchak** [comment]
@doug1234, indeed there is no need now to use objects.SecretdoorDetect. Removed that and made reference to secret_door directly in python_object. Thank you!!

**Comment by doug1234** [comment]
That change looks good.

**Comment by DudeMcDude** [comment]
> @doug1234, may I ask you to make code review? This is port from IDA, no changes.

Hmm, did you make sure to include the fix for seen scenery?

**Comment by anatoliy-savchak** [comment]
> Hmm, did you make sure to include the fix for seen scenery?
What fix?

**Comment by DudeMcDude** [comment]
What I mentioned in co8. I want to make sure this doesn't undo the fix for secret doors. Are you sure it doesn't?

**Comment by anatoliy-savchak** [comment]
@DudeMcDude, I have not touched that. Moreover there will be no changes in algorithms in comparison to previous implementation in toee.dll. I simply exposed them in T+.

This is your fix, right? It remains untouched.
```
uint32_t SecretDoorSys::secretDoorIsRevealed(objHndl secDoor)
{	// this function replacement should fix the motherfucking secretdoor bug
	// it worked on Aquinas' save!
	// The problem was that there's some sort of "revealed scenery" list which for some reason the secret door appears there
	// so I just removed that - there's the secret_door_found flag anyway
	// come to think of it, it may have supposed to prevent the player from searching again and again, but fuckit
	// they take 20 anyway (well maybe not in KotB >_>)
	if (!secDoor) return 0;
	uint32_t secDoorFlags = objects.getInt32(secDoor, obj_f_secretdoor_flags);
	if ( (secDoorFlags & OSDF_SECRET_DOOR) == 0 )  return 0;
	return (secDoorFlags & OSDF_SECRET_DOOR_FOUND) != 0;
	// there was also a look up in some name table, but that seems to be bugged (the door would already appear there in the secret door bug case, thus preventing its revelation)
}
```

**Pull request merged**
