### PR TITLE
Worldmap fixes

### PR DESCRIPTION
**Pull request by DudeMcDude**
@doug1234 
That's one of the WIP fixes I'd wanted for the next release.
IIRC there were two issues actually:
1. Travelling to one of the new Co8 locations from a random encounter map, when it's not the original destination of travel. See thread:
https://co8.org/community/index.php?threads/release-dllfix11.3940/
I think that's fully fixed.
2. Crash due to getting data from the terrain bitmap wrong. See thread:
https://co8.org/community/index.php?threads/terrain-bmp.11642/#post-148308
I think I fixed the immediate crash issue by reploacing the GetTerrainType func and making it safe. But I think I was having some trouble calculating the offsets into the bmp data in memory. As it is, Co8 ignores it anyway and just randomizes the terrain, but it'd be nice to make the worldmap bitmap great again.

### CODE REVIEW

**Comment by doug1234** [comment]
I am going to take another look at the first fix but it seems reasonable to me.

For the bitmap stuff, what are the magic numbers 528 and ?  The image is 264 x 283.  Also, what is up with shifting the image?

**Comment by DudeMcDude** [comment]
Right shift is basically divide by 2.

**Comment by doug1234** [comment]
I understand that you can integer multiply and divide by powers of 2 using left and right shift.  But I mixed up my left and right!  My question was more why does that need to be done to the array index.  I guess the answer is that the low bit is used as a flag?  

If I understand the issue properly this fixes a crash so it is much better than what was there.  However, it still isn't producing the right values.  If we can figure out how to get the right values we can improve the random encounters for temple+ by using a new encounter bitmap which we would need to make.  Sounds like a cool project for a future version.

**Comment by doug1234** [comment]
BTW:  Should this fix issue #233?

**Comment by DudeMcDude** [comment]
I'm not sure abiut the bitshift. I think i just copied the decompilation as is.

It would be nice to get proper x,y. You shouldn't have to generate a new bitmap, a proper solution should just scale it right. But i agree it's not critical for this release, the above is good enough I guess.

**Comment by doug1234** [comment]
Part of the issue with the bitmap calculation is using integer math:  "bitmapW * (y * bitmapH / 565)" is not going to give an accurate result.  We can try changing the calculation to use only doubles and convert to int at the last step.  That will fix at least some of the problem.

**Comment by doug1234** [comment]
I'll look into this one some more for next version.  But the crash is fixed so this is good for now.

**Pull request merged**
