### PR TITLE
Added power throw and brutal throw feats.

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by DudeMcDude** [comment]
Were you planning on adding more stuff? I ask because you often do :)

**Comment by doug1234** [comment]
I do indeed often do that. :) I have another feat I am working on but I think this one is ready to go as is.

**Comment by DudeMcDude** [comment]
Can you update the dat files? Sorry I didn't merge earlier.

**Comment by doug1234** [comment]
No problem.  Merged with the latest and updated the dat files.

**Pull request merged**
