### PR TITLE
Added back data pack.

### PR DESCRIPTION
**Pull request by doug1234**
Checking to see if it causes an issue with CI.

### CODE REVIEW

**Comment by doug1234** [comment]
Now builds correctly in CI and through running Visual Studio.  Should be good to do.

**Comment by DudeMcDude** [comment]
Have you checked that the files are valid? IIRC currently the infrastructure uses the recreated dat packer, which I think still had some diffs with the original one.

**Comment by doug1234** [comment]
I will take a little more them then and double check that the dat files made by the CI work the same.

**Comment by doug1234** [comment]
I checked that the ones in the artifact loaded.  It turns out I have been using the packer from dependencies for a while now and haven't had any issues.  Is there anything in particular you think I should test?

**Comment by DudeMcDude** [comment]
I just vaguely remember doing a bitwise comparison between our datpacker and the one that relies on tio.dll and seeing some differences. It could be that:
1. It got fixed in the meantime (by @shartte), so there are no more differences.
2. Errors are still present, but are subtle.
3. Differences exist, but they are meaningless.

So I guess the first step would be to check if there's still any diffs :)

**Comment by DudeMcDude** [comment]
Locally you mean?
Just to state the obvious, does it have tio.dll and the zip dll in the same folder?

**Comment by DudeMcDude** [comment]
Ah, one thing I can think of - which version of tio.dll are you using? It needs the one dated 2004-10-12 (CRC2 = 2E1CB46B, available in GoG, not the patch2 version)

**Comment by doug1234** [comment]
The dll is indeed dated 2005-10-12.

**Comment by DudeMcDude** [comment]
Alright i finally got around to comparing the results myself. Looks ok (as far as i can tell the diffs are just due to uninitialized data in fixed size null terminated strings, which should be of no consequence).

**Comment by doug1234** [comment]
Thanks a ton for doing that!  This should make things easier going forward.

**Pull request merged**
