### PR TITLE
Added Divine Armor Feat

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by doug1234** [comment]
Were you referring to divine_spell_level_can_cast?  I don't think I tried that.  I'll see if it work tomorrow.

**Comment by DudeMcDude** [comment]
My mistake, it checks what spell level you can cast. It was required for some prestige classes like Mystic Theurge.

But it should be fairly easy to create GetDivineCasterLevel by iterating all classes and checking IsDivineCastingClass.

**Comment by doug1234** [comment]
Future proofing is a good argument.  I added the properties to the python objects.

**Comment by doug1234** [comment]
I went ahead and added divine vigor also since I had it ready to go.

**Comment by doug1234** [comment]
The divine vigor bonus now has a string.

**Comment by doug1234** [comment]
Added the divine shield feat.

**Pull request merged**
